# Exercises for Week 1 of mathematics for Data Science

## 2 Computational Aspects of Linear Algebra

### 2.1.

In [2]:
import numpy as np

In [3]:
A = np.array([[-1, 2, 3, 3, 2, 1],
             [-1, -2, 3, 3, 2, 1],
             [-1, -2, -3, 3, 2, 1],
             [-1, -2, -3, -3, 2, 1],
             [-1, -2,- 3, -3, -2, 1],
             [1, 2, 3, 3, 2, 1]])
B = np.array([[-1, 1, 3, 3, 1, 1],
             [-1, -1, 3, 3, 1, 1],
             [-1, -1, -3, 3, 1, 1],
             [-1, -1, -3, -3, 1, 1],
             [-1, -1, -3, -3, -1, 1],
             [1, 1, 3, 3, 1, 1]])

In [4]:
C = A + 2 * B
C

array([[-3,  4,  9,  9,  4,  3],
       [-3, -4,  9,  9,  4,  3],
       [-3, -4, -9,  9,  4,  3],
       [-3, -4, -9, -9,  4,  3],
       [-3, -4, -9, -9, -4,  3],
       [ 3,  4,  9,  9,  4,  3]])

In [5]:
D = 7 * A - 8 * B
D

array([[ 1,  6, -3, -3,  6, -1],
       [ 1, -6, -3, -3,  6, -1],
       [ 1, -6,  3, -3,  6, -1],
       [ 1, -6,  3,  3,  6, -1],
       [ 1, -6,  3,  3, -6, -1],
       [-1,  6, -3, -3,  6, -1]])

In [10]:
E = A * B
E

array([[1, 2, 9, 9, 2, 1],
       [1, 2, 9, 9, 2, 1],
       [1, 2, 9, 9, 2, 1],
       [1, 2, 9, 9, 2, 1],
       [1, 2, 9, 9, 2, 1],
       [1, 2, 9, 9, 2, 1]])

In [14]:
F = np.invert(E) * D.T
F

array([[ -2,  -3, -10, -10,  -3,   2],
       [-12,  18,  60,  60,  18, -12],
       [  6,   9, -30, -30,  -9,   6],
       [  6,   9,  30, -30,  -9,   6],
       [-12, -18, -60, -60,  18, -12],
       [  2,   3,  10,  10,   3,   2]])

In [19]:
np.random.seed(8012018)
N = 100

X = np.array([np.random.uniform(0.95, 1.25, N),
             np.random.uniform(0.45, 0.75, N),
             np.random.uniform(0.60, 1, N),
             np.random.uniform(1.85, 2.45, N)])
y = np.array([3 * np.ones([N])])

This is a compoutashone